server:
  port: 9900
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/yimeichonggou?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

  #开启热部署
  #重启目录
#  spring.devtools.restart.enabled=true

#  spring.devtools.restart.additional-paths=src/main/java
#  spring.devtools.restart.exclude=WEB-INF/**


#本项目是一个 springBoot + vue + mybatis的一个脚手架,
#集成了权限系统,代码生成器,图片上传,登录,注册功能